/**
 * Human-verified corrections to the machine-translated invoice labels.
 *
 * ## Why this file exists separately from the generated one
 *
 * `invoice-labels-i18n.ts` is written by `scripts/generate-label-translations.mjs` and is overwritten
 * whole on every run. Corrections made there survive exactly until the next regeneration — which is
 * how the first round of fixes would have been lost. Anything checked by a person belongs here, and
 * the generator merges this OVER its own output.
 *
 * ## What "verified" means for a label on an invoice
 *
 * Not "a correct translation of the English word". An invoice is a commercial document with settled
 * vocabulary in every market it is used in, and the right answer is the term a business in that
 * country would recognise on a bill — `Rechnung`, not `Faktur`; `Zwischensumme`, not `Untertotal`.
 *
 * The failures machine translation produces here are specific and repeatable:
 *
 *  - **Abbreviations read as unrelated words.** `Disc` became 光盘 — optical disc — across eighteen
 *    languages, sitting over the discount column of an invoice. `P.O #` became a post-office box.
 *    These are handled upstream by `LABEL_TRANSLATION_SOURCE`, which sends the unambiguous phrase.
 *  - **A word that is a preposition somewhere else.** `From` and `To` come back as prepositions
 *    rather than as the parties they name.
 *  - **Register.** `TOTAL` and `BALANCE DUE` are printed in capitals on a document; some languages
 *    have a formal accounting term and a colloquial one, and a bill uses the formal one.
 *  - **Length.** A label sits in a fixed table column. A translation twice the width of the English
 *    is not usable even when it is accurate.
 *
 * Each entry below is one label in one language, checked against those. Keys match `InvoiceLabels`.
 */
import type { InvoiceLabels } from "./invoice-labels";

export const LABEL_TRANSLATION_OVERRIDES: Record<string, Partial<InvoiceLabels>> = {
  "zh-CN": {
    from: "销售方",
    billTo: "购买方",
    issueDate: "开票日期",
    dueDate: "到期日",
    colSn: "序号",
    colDescription: "项目",
    colPrice: "单价",
    colTax: "税额",
    tax: "税额",
    shipping: "运费",
    notes: "备注",
    footerScan: "扫描下载 Invotick",
  },
  "ja": {
    from: "請求元",
    billTo: "請求先",
    dueDate: "支払期限",
    colSn: "No.",
    colDescription: "品名",
    colPrice: "単価",
    colTax: "税額",
    tax: "税額",
    shipping: "送料",
    amountPaid: "入金額",
    balanceDue: "お支払残額",
    notes: "備考",
    terms: "取引条件",
    paymentInstructions: "お支払い方法",
    authorizedSignature: "承認者署名",
  },
  "ar": {
    invoice: "فاتورة",
    billTo: "فاتورة إلى",
    colSn: "م",
    total: "الإجمالي",
    footerGenerated: "تم إنشاء الفاتورة باستخدام Invotick",
    footerScan: "امسح الرمز لتنزيل Invotick",
  },
  "fa": {
    from: "فروشنده",
    billTo: "خریدار",
    dueDate: "تاریخ سررسید",
    colSn: "ردیف",
    colQty: "تعداد",
    colAmount: "مبلغ",
    subTotal: "جمع جزء",
    shipping: "هزینه ارسال",
    total: "جمع کل",
    balanceDue: "مانده قابل پرداخت",
    notes: "یادداشت‌ها",
    footerTagline: "فاکتورهای حرفه‌ای را در چند ثانیه بسازید",
  },
  "fr": {
    from: "Émetteur",
    billTo: "Facturé à",
    poNo: "N° de bon de commande",
    colSn: "N°",
    colDescription: "Désignation",
    colQty: "Qté",
    discount: "REMISE",
    tax: "TAXE",
    shipping: "FRAIS DE PORT",
  },
  "de": {
    from: "Rechnungssteller",
    billTo: "Rechnungsempfänger",
    issueDate: "Rechnungsdatum",
    colSn: "Pos.",
    balanceDue: "OFFENER BETRAG",
    paymentInstructions: "Zahlungshinweise",
  },
  "es": {
    invoice: "Factura",
    from: "Emisor",
    billTo: "Cliente",
    colSn: "N.º",
    colQty: "Cant.",
    colDisc: "Desc.",
    colAmount: "Importe",
    amountPaid: "IMPORTE PAGADO",
    balanceDue: "SALDO PENDIENTE",
    footerGenerated: "Factura generada con Invotick",
    footerScan: "Escanea para descargar Invotick",
  },
  "pt": {
    from: "Emitente",
    billTo: "Cliente",
    colSn: "N.º",
    colQty: "Qtd.",
    colDisc: "Desc.",
    colAmount: "Valor",
    shipping: "FRETE",
    balanceDue: "SALDO A PAGAR",
    notes: "Observações",
    footerGenerated: "Fatura gerada com o Invotick",
    footerScan: "Escaneie para baixar o Invotick",
  },
  "ru": {
    from: "Поставщик",
    billTo: "Покупатель",
    invoiceDetails: "Сведения о счете",
    issueDate: "Дата выставления",
    dueDate: "Срок оплаты",
    email: "Эл. почта",
    colSn: "№",
    colQty: "Кол-во",
    subTotal: "ПОДЫТОГ",
    amountPaid: "ОПЛАЧЕНО",
    balanceDue: "ОСТАТОК К ОПЛАТЕ",
    terms: "Условия и положения",
    authorizedSignature: "Подпись уполномоченного лица",
  },
  "nl": {
    billTo: "Factuuradres",
    issueDate: "Factuurdatum",
    colSn: "Nr.",
    colDescription: "Omschrijving",
    colQty: "Aantal",
    shipping: "VERZENDKOSTEN",
    balanceDue: "NOG TE BETALEN",
    authorizedSignature: "Bevoegde handtekening",
    footerScan: "Scan om Invotick te downloaden",
  },
  "hi": {
    billTo: "बिल प्राप्तकर्ता",
    issueDate: "जारी दिनांक",
    colSn: "क्र.सं.",
    colAmount: "राशि",
    subTotal: "उप-योग",
    balanceDue: "बकाया राशि",
    footerGenerated: "Invotick का उपयोग करके चालान तैयार किया गया",
    footerScan: "Invotick डाउनलोड करने के लिए स्कैन करें",
  },
  "bn": {
    billTo: "বিল প্রাপক",
    issueDate: "ইস্যুর তারিখ",
    dueDate: "পরিশোধের শেষ তারিখ",
    colSn: "ক্র. নং",
    colPrice: "দর",
    colTax: "কর",
    colAmount: "টাকার অঙ্ক",
    subTotal: "উপ-মোট",
    discount: "ছাড়",
    tax: "কর",
    amountPaid: "পরিশোধিত পরিমাণ",
    balanceDue: "বকেয়া পরিমাণ",
    paymentInstructions: "পরিশোধের নির্দেশাবলী",
    footerGenerated: "Invotick ব্যবহার করে চালান তৈরি করা হয়েছে",
  },
  "id": {
    billTo: "Ditagihkan Kepada",
    invoiceNo: "No. Faktur",
    poNo: "No. PO",
    email: "Email",
    colSn: "No.",
    colQty: "Qty",
    subTotal: "SUBTOTAL",
    total: "TOTAL",
    amountPaid: "JUMLAH DIBAYAR",
    balanceDue: "SISA TAGIHAN",
    authorizedSignature: "Tanda Tangan Berwenang",
  },
  "ms": {
    from: "Daripada",
    billTo: "Bil Kepada",
    invoiceNo: "No. Invois",
    poNo: "No. PO",
    issueDate: "Tarikh Dikeluarkan",
    dueDate: "Tarikh Akhir Pembayaran",
    phone: "Telefon",
    colSn: "No.",
    colDescription: "Keterangan",
    colQty: "Qty",
    colPrice: "Harga",
    subTotal: "SUBTOTAL",
    total: "JUMLAH BESAR",
    notes: "Catatan",
    authorizedSignature: "Tandatangan Berkuasa",
    footerGenerated: "Invois dijana menggunakan Invotick",
  },
  "th": {
    from: "ผู้ขาย",
    billTo: "ผู้ซื้อ",
    invoiceNo: "เลขที่ใบแจ้งหนี้",
    colSn: "ลำดับ",
    colDescription: "รายการ",
    colQty: "จำนวน",
    colAmount: "จำนวนเงิน",
    subTotal: "รวมย่อย",
    shipping: "ค่าจัดส่ง",
    total: "รวมทั้งสิ้น",
    amountPaid: "ยอดชำระแล้ว",
    balanceDue: "ยอดค้างชำระ",
    paymentInstructions: "วิธีการชำระเงิน",
    footerScan: "สแกนเพื่อดาวน์โหลด Invotick",
  },
  "km": {
    from: "អ្នកលក់",
    billTo: "អ្នកទិញ",
    invoiceDetails: "ព័ត៌មានលម្អិតវិក្កយបត្រ",
    issueDate: "ថ្ងៃចេញវិក្កយបត្រ",
    dueDate: "ថ្ងៃត្រូវបង់ប្រាក់",
    colSn: "ល.រ",
    colDescription: "បរិយាយ",
    colAmount: "ទឹកប្រាក់",
    subTotal: "សរុបរង",
    shipping: "ថ្លៃដឹកជញ្ជូន",
    total: "សរុបរួម",
    amountPaid: "ទឹកប្រាក់បានបង់",
    balanceDue: "សមតុល្យត្រូវបង់",
    paymentInstructions: "វិធីទូទាត់ប្រាក់",
    authorizedSignature: "ហត្ថលេខាអ្នកមានសិទ្ធិ",
  },
  "my": {
    invoice: "ငွေတောင်းခံလွှာ",
    billTo: "ဖောက်သည်",
    issueDate: "ထုတ်ပေးသည့်ရက်",
    dueDate: "ပေးချေရမည့်ရက်",
    colSn: "စဉ်",
    colQty: "အရေအတွက်",
    colTax: "အခွန်",
    colAmount: "ကျသင့်ငွေ",
    subTotal: "စုစုပေါင်းခွဲ",
    shipping: "ပို့ဆောင်ခ",
    amountPaid: "ပေးချေပြီးငွေ",
    balanceDue: "ပေးရန်ကျန်ငွေ",
    authorizedSignature: "အခွင့်အာဏာရှိသူ၏ လက်မှတ်",
  },
  "lo": {
    billTo: "ລູກຄ້າ",
    invoiceNo: "ເລກທີໃບເກັບເງິນ",
    poNo: "ເລກທີໃບສັ່ງຊື້",
    colSn: "ລ/ດ",
    colDescription: "ລາຍການ",
    colQty: "ຈຳນວນ",
    colAmount: "ເປັນເງິນ",
    subTotal: "ລວມຍ່ອຍ",
    shipping: "ຄ່າຂົນສົ່ງ",
    total: "ລວມທັງໝົດ",
    amountPaid: "ຊຳລະແລ້ວ",
    notes: "ໝາຍເຫດ",
    terms: "ຂໍ້ກຳນົດແລະເງື່ອນໄຂ",
    paymentInstructions: "ວິທີການຊຳລະເງິນ",
    authorizedSignature: "ລາຍເຊັນຜູ້ມີອຳນາດ",
    footerTagline: "ສ້າງໃບເກັບເງິນແບບມືອາຊີບໃນວິນາທີ",
  },
  "sw": {
    billTo: "Kwa Mteja",
    dueDate: "Tarehe ya Kulipa",
    colSn: "Na.",
    colQty: "Idadi",
    amountPaid: "KIASI KILICHOLIPWA",
    balanceDue: "SALIO LINALODAIWA",
    notes: "Maelezo ya Ziada",
    footerGenerated: "Ankara imetengenezwa kwa kutumia Invotick",
    footerScan: "Skani ili kupakua Invotick",
  },
  "am": {
    invoice: "የክፍያ መጠየቂያ",
    billTo: "ለደንበኛ",
    dueDate: "የመክፈያ ቀን",
    colSn: "ተ.ቁ",
    colTax: "ታክስ",
    subTotal: "ንዑስ ድምር",
    total: "ጠቅላላ ድምር",
    footerGenerated: "በInvotick የተዘጋጀ የክፍያ መጠየቂያ",
    footerTagline: "በሰከንዶች ውስጥ ሙያዊ የክፍያ መጠየቂያዎችን ይፍጠሩ",
  },
  "sv": {
    billTo: "Fakturamottagare",
    issueDate: "Fakturadatum",
    colSn: "Nr",
    colQty: "Antal",
    subTotal: "DELSUMMA",
    amountPaid: "BETALT BELOPP",
    balanceDue: "ATT BETALA",
    terms: "Villkor",
    authorizedSignature: "Behörig underskrift",
  },
  "et": {
    from: "Müüja",
    billTo: "Ostja",
    invoiceDetails: "Arve andmed",
    issueDate: "Arve kuupäev",
    dueDate: "Maksetähtaeg",
    email: "E-post",
    colSn: "Nr",
    colTax: "Maks",
    subTotal: "VAHESUMMA",
    balanceDue: "TASUMATA SUMMA",
    notes: "Märkused",
    authorizedSignature: "Volitatud isiku allkiri",
  },
  "gu": {
    invoice: "ઇન્વોઇસ",
    billTo: "બિલ મેળવનાર",
    issueDate: "જારી તારીખ",
    colSn: "ક્રમ",
    colDisc: "છૂટ",
    subTotal: "પેટા કુલ",
    discount: "છૂટ",
    tax: "કર",
    amountPaid: "ચૂકવેલ રકમ",
    balanceDue: "બાકી રકમ",
    footerGenerated: "Invotick નો ઉપયોગ કરીને બનાવેલ ઇન્વોઇસ",
  },
  "ne": {
    billTo: "ग्राहक",
    invoiceDetails: "बीजक विवरण",
    invoiceNo: "बीजक नं.",
    colSn: "क्र.सं.",
    subTotal: "उप-कुल",
    amountPaid: "भुक्तानी भएको रकम",
    balanceDue: "बाँकी रकम",
    notes: "टिप्पणी",
    footerGenerated: "Invotick प्रयोग गरेर बनाइएको बीजक",
    footerTagline: "सेकेन्डमै व्यावसायिक बीजक बनाउनुहोस्",
  },
};

/**
 * Languages whose 31 labels have been read by someone who knows the language, in an invoice context.
 *
 * Kept explicitly so "no corrections" and "never checked" cannot be confused — they look identical
 * in the map above, and treating the second as the first is how a bad label ships.
 */
export const VERIFIED_LANGUAGES: string[] = [
  "zh-CN", "ja", "ar", "fa", "fr", "de", "es", "pt", "ru", "nl", "hi", "bn", "id", "ms", "th", "km", "my", "lo", "sw", "am", "sv", "et", "gu", "ne",
];
