// One-click demo invoices. Each sample is tied to the invoice template that
// matches its industry, so "Surprise me" produces a coherent result — the
// header design, the business and the line items all belong together.
import type { FreeInvoice } from "./types";
import { createEmptyInvoice, nextInvoiceNumber, uuid } from "./adapter";
import { templateById } from "./templates";

type Sample = Pick<
  FreeInvoice,
  | "businessName" | "businessAddress" | "businessEmail" | "businessPhone"
  | "clientName" | "clientAddress" | "clientEmail"
  | "taxRate" | "discountValue" | "shippingCost" | "notes" | "terms" | "currency"
> & { templateId: string; items: Array<{ description: string; quantity: string; rate: string }> };

const SAMPLES: Sample[] = [
  {
    templateId: "creative",
    businessName: "Pixel & Co. Design Studio",
    businessAddress: "48 Maple Street, Brooklyn, NY 11201",
    businessEmail: "hello@pixelco.studio",
    businessPhone: "+1 (718) 555-0142",
    clientName: "Northwind Traders",
    clientAddress: "900 Market St, San Francisco, CA 94103",
    clientEmail: "accounts@northwind.co",
    taxRate: "8.5",
    discountValue: "",
    shippingCost: "",
    notes: "Thank you for your business! Payment via bank transfer or card.",
    terms: "Payment due within 14 days.",
    currency: "USD",
    items: [
      { description: "Brand identity & logo design", quantity: "1", rate: "1800" },
      { description: "Website UI design (12 screens)", quantity: "12", rate: "150" },
      { description: "Social media templates", quantity: "1", rate: "450" },
    ],
  },
  {
    templateId: "business",
    businessName: "Meridian Consulting",
    businessAddress: "1200 Corporate Blvd, Chicago, IL 60601",
    businessEmail: "invoices@meridian-consult.com",
    businessPhone: "+1 (312) 555-0176",
    clientName: "Vertex Manufacturing",
    clientAddress: "55 Industrial Pkwy, Detroit, MI 48201",
    clientEmail: "finance@vertexmfg.com",
    taxRate: "6",
    discountValue: "",
    shippingCost: "",
    notes: "Retainer covers July 2026 advisory hours.",
    terms: "Net 30.",
    currency: "USD",
    items: [
      { description: "Strategy consulting (senior)", quantity: "24", rate: "220" },
      { description: "Process audit & report", quantity: "1", rate: "2400" },
    ],
  },
  {
    templateId: "electronics",
    businessName: "TechHub Electronics",
    businessAddress: "14 Camden High St, London NW1 0JH",
    businessEmail: "service@techhub.co.uk",
    businessPhone: "+44 20 7946 0521",
    clientName: "Bright Offices Ltd",
    clientAddress: "5 Canary Wharf, London E14 5AB",
    clientEmail: "admin@brightoffices.co.uk",
    taxRate: "20",
    discountValue: "",
    shippingCost: "",
    notes: "90-day warranty on all repairs.",
    terms: "Payment due on collection.",
    currency: "GBP",
    items: [
      { description: "Laptop screen replacement", quantity: "3", rate: "160" },
      { description: "Battery replacement", quantity: "3", rate: "75" },
      { description: "Data backup & setup", quantity: "3", rate: "40" },
    ],
  },
  {
    templateId: "medical",
    businessName: "Wellness Medical Clinic",
    businessAddress: "230 Health Ave, Austin, TX 78701",
    businessEmail: "billing@wellnessclinic.com",
    businessPhone: "+1 (512) 555-0134",
    clientName: "Daniel Foster",
    clientAddress: "88 Oak Ridge Dr, Austin, TX 78704",
    clientEmail: "d.foster@email.com",
    taxRate: "",
    discountValue: "",
    shippingCost: "",
    notes: "Please bring this invoice for insurance reimbursement.",
    terms: "Payment due on receipt.",
    currency: "USD",
    items: [
      { description: "General consultation", quantity: "1", rate: "120" },
      { description: "Blood panel & lab tests", quantity: "1", rate: "180" },
      { description: "ECG procedure", quantity: "1", rate: "95" },
    ],
  },
  {
    templateId: "automotive",
    businessName: "Prestige Auto Garage",
    businessAddress: "72 Kingsway, Manchester M1 4BT",
    businessEmail: "service@prestigeauto.co.uk",
    businessPhone: "+44 161 555 0198",
    clientName: "James Whitfield",
    clientAddress: "19 Elm Grove, Manchester M14 5RB",
    clientEmail: "j.whitfield@email.com",
    taxRate: "20",
    discountValue: "",
    shippingCost: "",
    notes: "Next service due in 12 months or 10,000 miles.",
    terms: "Payment due on collection.",
    currency: "GBP",
    items: [
      { description: "Full service (labour)", quantity: "1", rate: "220" },
      { description: "Front brake pads (set)", quantity: "1", rate: "140" },
      { description: "Oil & filter change", quantity: "1", rate: "65" },
      { description: "Diagnostics check", quantity: "1", rate: "45" },
    ],
  },
  {
    templateId: "workshop",
    businessName: "Coastal Plumbing Services",
    businessAddress: "31 Wharf Street, Sydney NSW 2000",
    businessEmail: "jobs@coastalplumbing.au",
    businessPhone: "+61 2 5550 0143",
    clientName: "Ridgeway Apartments",
    clientAddress: "88 Ocean View Rd, Bondi NSW 2026",
    clientEmail: "strata@ridgeway.au",
    taxRate: "10",
    discountValue: "",
    shippingCost: "",
    notes: "Emergency call-out completed same day.",
    terms: "Payment due on receipt.",
    currency: "AUD",
    items: [
      { description: "Emergency leak repair — labour", quantity: "4", rate: "95" },
      { description: "Replacement parts & fittings", quantity: "1", rate: "260" },
      { description: "Call-out fee", quantity: "1", rate: "80" },
    ],
  },
  {
    templateId: "safety",
    businessName: "BuildRight Contractors",
    businessAddress: "500 Commerce Way, Denver, CO 80202",
    businessEmail: "accounts@buildright.com",
    businessPhone: "+1 (303) 555-0187",
    clientName: "Summit Property Group",
    clientAddress: "1400 Lawrence St, Denver, CO 80202",
    clientEmail: "projects@summitpg.com",
    taxRate: "7.5",
    discountValue: "",
    shippingCost: "",
    notes: "Progress billing — phase 2 of 4.",
    terms: "Net 30.",
    currency: "USD",
    items: [
      { description: "Site labour (crew, per day)", quantity: "10", rate: "1200" },
      { description: "Materials & supplies", quantity: "1", rate: "8600" },
      { description: "Equipment hire", quantity: "1", rate: "2400" },
    ],
  },
  {
    templateId: "builder",
    businessName: "Redstone Masonry",
    businessAddress: "24 Quarry Lane, Leeds LS1 4DR",
    businessEmail: "info@redstonemasonry.co.uk",
    businessPhone: "+44 113 555 0164",
    clientName: "Hartley Developments",
    clientAddress: "9 Riverside, Leeds LS1 4AP",
    clientEmail: "accounts@hartleydev.co.uk",
    taxRate: "20",
    discountValue: "",
    shippingCost: "",
    notes: "Brickwork for the rear extension, as quoted.",
    terms: "50% deposit received. Balance due on completion.",
    currency: "GBP",
    items: [
      { description: "Bricklaying — labour (day)", quantity: "8", rate: "260" },
      { description: "Bricks, cement & sand", quantity: "1", rate: "1850" },
      { description: "Scaffolding hire", quantity: "1", rate: "600" },
    ],
  },
  {
    templateId: "fashion",
    businessName: "Velvet Boutique",
    businessAddress: "12 Rue Saint-Honoré, 75001 Paris",
    businessEmail: "atelier@velvetboutique.fr",
    businessPhone: "+33 1 42 55 01 90",
    clientName: "Amélie Laurent",
    clientAddress: "34 Avenue Montaigne, 75008 Paris",
    clientEmail: "amelie.laurent@email.com",
    taxRate: "20",
    discountValue: "10",
    shippingCost: "15",
    notes: "Fittings included. Alterations within 30 days free.",
    terms: "Payment due on receipt.",
    currency: "EUR",
    items: [
      { description: "Evening gown (bespoke)", quantity: "1", rate: "890" },
      { description: "Alterations & tailoring", quantity: "1", rate: "120" },
      { description: "Personal styling session", quantity: "1", rate: "150" },
    ],
  },
];

export function randomSample(): FreeInvoice {
  const s = SAMPLES[Math.floor(Math.random() * SAMPLES.length)];
  const t = templateById(s.templateId);
  return {
    ...createEmptyInvoice(),
    ...s,
    invoiceNumber: nextInvoiceNumber(),
    items: s.items.map((it) => ({ id: uuid(), ...it })),
    // Apply the industry-matched template so header + colour fit the business.
    templateId: t.id,
    headerImage: t.headerImage,
    color: t.color,
    titleColor: t.titleColor ?? null,
  };
}
