import { NextResponse } from "next/server";
import { isWebEventName, sanitiseParams } from "@/lib/analytics/events";
import { platformFromUserAgent } from "@/lib/analytics/platform";
import { allowEvent, callerKey } from "@/lib/analytics/rate-limit";
import { sendWebAnalyticsEvent } from "@/lib/analytics/send";

/**
 * The session id is generated by the browser, so it is validated rather than trusted: the backend
 * binds it through `UUID_TO_BIN`, and a string that is not a UUID fails there instead of here —
 * inside the transaction that also writes the event.
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * The one door between the public share page and `/v2/analytics/track`.
 *
 * Same shape as the `/viewed` and `/decision` routes next door, for the same reasons: the browser
 * talks to its own origin, the backend URL never reaches the client, and there is a server-side
 * place to put the checks. Sending events straight from the browser to the backend would need CORS
 * and would leave nowhere to stand.
 *
 * Three things are decided HERE and never taken from the body:
 *
 * - the **event id**, because supplying one lets a caller overwrite an existing analytics row;
 * - the **surface** and **viewer platform**, because a value the client cannot supply is one fewer
 *   thing to verify — and the platform read from this request's own User-Agent is the same one the
 *   page branched its buttons on;
 * - the **country**, from the edge header, when the platform gives one.
 *
 * The body may carry only an event name from the fixed list and parameters that match its schema.
 * Anything else is refused, not trimmed and stored.
 *
 * Always answers fast and never surfaces a failure to the receiver. `202` means "we took it", not
 * "it was stored" — the backend can still refuse a batch and answer 200 with zero written (see
 * `AnalyticsVersionGate`), which is exactly why the web pipeline needed its own gate change before
 * this could work at all.
 */
export async function POST(request: Request) {
  const headers = request.headers;

  if (!allowEvent(callerKey(headers))) {
    // No detail, no Retry-After. This is telemetry about someone else's invoice; a caller probing
    // the limit learns nothing from us.
    return new NextResponse(null, { status: 429 });
  }

  const body = (await request.json().catch(() => null)) as {
    event?: unknown;
    sessionId?: unknown;
    params?: unknown;
  } | null;

  const name = body?.event;
  if (!isWebEventName(name)) {
    return NextResponse.json({ error: "unknown event" }, { status: 400 });
  }

  const sessionId = body?.sessionId;
  if (typeof sessionId !== "string" || !UUID_RE.test(sessionId)) {
    return NextResponse.json({ error: "sessionId must be a uuid" }, { status: 400 });
  }

  const params = sanitiseParams(name, body?.params);
  if (params === null) {
    return NextResponse.json({ error: "params do not match the event" }, { status: 400 });
  }

  await sendWebAnalyticsEvent({
    eventName: name,
    params,
    sessionId,
    viewerPlatform: platformFromUserAgent(headers.get("user-agent")),
    country: headers.get("x-vercel-ip-country"),
  });

  return new NextResponse(null, { status: 202 });
}
